# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
#  - osx
#  - windows
r:
  - oldrel
  - release
  - devel
r_packages:
  - Rmpi
addons:
  apt:
    packages:
      mpi-default-dev
      mpi-default-bin
  homebrew:
    packages:
      open-mpi
after_success:
  - Rscript -e 'covr::codecov()'
